'use client'
import { AuthContextProvider } from '@/context/AuthContext'
import '../globals.css'
import { AppBar, Box, Drawer, IconButton, Toolbar } from '@mui/material'
import MenuIcon from '@mui/icons-material/Menu';
import { useState } from 'react';

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
    const [ openDrawer, setOpenDrawer ] = useState(true)
    const toggleDrawer = (anchor, open) => (event) => {
        if (event.type == 'keydown' && (event.key === 'Tab' || event.key == 'Shift')) {
            return;
        }
    }
  return (

        <Box sx={{flexGrow:1}}>
            <Drawer
                anchor='left'
                open={openDrawer}
                onClose={toggleDrawer}
            >
                this is a test
            </Drawer>
            <AppBar position='relative'>
                <Toolbar>
                    <IconButton>
                        <MenuIcon sx={{color:'#fff'}}/>
                    </IconButton>
                </Toolbar>
            </AppBar>
                <AuthContextProvider>
                    {children}
                </AuthContextProvider>
        </Box>

  )
}